name: Ping Render App

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes (UTC)
  workflow_dispatch: # Optional: manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping your Render app
        run: curl -I https://library-analytics-api.onrender.com
