name: Ping Render App

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:        # Optional: allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP GET request to Render app
        run: |
          curl -I https://library-analytics-api.onrender.com
